server:
  port: 8085

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev

startRoute: timer:hello?period=10s
fromRoute : file:data/input?delete=true&readLock=none
toRoute1: file:data/output

message: DEV Environment

---
spring:
  profiles: stage

startRoute: timer:hello?period=10s
fromRoute : file:data/input?delete=true&readLock=none
toRoute1: file:data/output

message: STAGE Environment

---
spring:
  profiles: prod

startRoute: timer:hello?period=10s
fromRoute : file:data/input?delete=true&readLock=none
toRoute1: file:data/output


message: PROD Environment
---